apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: us.icr.io/$SN_ICR_NAMESPACE/accounts:1
          env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database-password
          - name: DATABASE_HOST
            value: "postgresql"  